server:
  port: 8081
#  ssl:
#    key-store: classpath:config/baotian.club.jks
#    key-store-password: BAOtiandi789
#    key-store-type: jks
#    key-alias: baotianclub
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    mode: LEGACYHTML5
    encoding: utf-8
  profiles:
    active: dev
#  jpa:
#    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  #context-path: "actuator" ###配置前缀
#  mybatis:
#    config-location: classpath:mybatis/mybatis-config.xml
#    mapper-locations: classpath:mybatis/mapper/*.xml
#Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jxy.study.entity
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    cache-enabled: true #开启二级缓存
security:
  shiro:
    urlFilterMap:
      /logout: logout
      /login: login
      /getRoleById: user
      /mainPage: user
      /rest/*: jwt,user,perm
#      /test/**: anno

project:
  main_page: homePage
  loginUrl: /login
  loginSuccess: /
  login_html: loginBeifen
  cookie_time: 2592000